In [2]:
import numpy as np

# 定义映射函数
def map_func(char):
    if char == ".":
        return 0
    elif char.isdigit():
        return int(char)
    elif char == "A":
        return 0
    else:
        raise ValueError(f"Invalid character {char}")

# 打开文件并读取每一行，并对每一行进行映射转换
with open("1.txt", "r") as f:
    result = np.array([list(map(map_func, line.strip())) for line in f])

print(result)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
x, y = result.nonzero()
print(x,y)

[ 2  2  2  2  2  2  2  2 20 31 31 31 31 36 49 49 49 62 67 67 67 67 78 97
 97 97 97 97 97 97 97] [ 2  6 10 44 55 89 93 97 49 18 26 73 81 49 34 49 64 49 18 26 73 81 49  2
  6 10 44 55 89 93 97]


In [4]:
xy = np.stack((x,y),-1)
XY = xy[:, None] - xy[None, :]
XY = np.linalg.norm(XY,2,-1)
print(XY)

[[  0.           4.           8.          42.          53.
   87.          91.          95.          50.32891813  33.12099032
   37.64306045  76.69419796  84.1546196   58.00862005  56.8594759
   66.46803743  77.80102827  76.21679605  66.94027188  69.28924881
   96.26006441 102.30347013  89.35882721  95.          95.08417324
   95.33624704 103.8701112  108.78419003 128.81770065 131.55227098
  134.35028843]
 [  4.           0.           4.          38.          49.
   83.          87.          91.          46.61544808  31.38470965
   35.22782991  73.00684899  80.41144197  54.81788029  54.70831747
   63.70243323  74.65252842  73.81734214  66.09841148  68.00735254
   93.34880824  99.24716621  87.32124598  95.08417324  95.
   95.08417324 102.31813134 106.89246933 126.15070353 128.81770065
  131.55227098]
 [  8.           4.           0.          34.          45.
   79.          83.          87.          42.95346319  30.08321791
   33.12099032  69.35416354  76.69419796  51.73973328  52.77309