In [4]:
import numpy as np

# 任务依赖关系
dependency = {
    7: [6, 5, 4],
    6: [2, 3],
    5: [1, 3],
    4: [1, 2],
    3: [],
    2: [],
    1: [],
}

# 任务所需时间
time = {
    7: 1000,
    6: 500,
    5: 500,
    4: 500,
    3: 50,
    2: 50,
    1: 50
}

# 工作台数量
stations = {
    7: 1,
    6: 2,
    5: 2,
    4: 2,
    3: 3,
    2: 3,
    1: 3
}

# 总时间限制
total_time = 8000

# 初始化任务矩阵
num_tasks = len(dependency)
tasks = np.zeros((num_tasks, num_tasks), dtype=int)

# 填充任务矩阵
for i in range(1, num_tasks + 1):
    for j in dependency[i]:
        tasks[j-1, i-1] = time[i]

# 初始化完成时间矩阵和任务安排矩阵
finish_time = np.zeros((num_tasks,), dtype=int)
schedule = np.zeros((num_tasks,), dtype=int)

# 对7号任务进行排序
sorted_indices = np.argsort(tasks[:, 6])[::-1]

# 初始化任务计划列表
task_plan = []

# 依次进行任务调度
for task in sorted_indices:
    # 找到可用的工作台
    available_stations = []
    for i in range(num_tasks):
        if tasks[i, task] != 0 and finish_time[i] <= total_time - tasks[i, task]:
            available_stations.append(i)
    # 如果没有可用的工作台，则跳过该任务
    if len(available_stations) == 0:
        continue
    # 选择最早空闲的工作台
    station_times = [finish_time[i] for i in available_stations]
    station = available_stations[np.argmin(station_times)]
    # 更新任务完成时间和任务安排
    finish_time[station] += tasks[station, task]
    schedule[task] = station + 1
    task_plan.append((finish_time[station], task + 1))

# 输出结果
print("任务完成时间：", finish_time)
print("7号任务完成时间：", finish_time[6])
print("任务安排：", schedule)
print("任务计划：")
for plan in task_plan:
    print(plan)

任务完成时间： [1000  500    0 1000    0    0    0]
7号任务完成时间： 0
任务安排： [0 0 0 1 1 2 4]
任务计划：
(500, 6)
(500, 5)
(1000, 4)
(1000, 7)


In [42]:
import numpy as np

# 任务依赖关系表，用字典表示
dependency_dict = {
    9: [(7, 6, 5, 4)],
    8: [7],
    7: [6, 5, 4],
    6: [2, 3],
    5: [1, 3],
    4: [1, 2],
    3: [],
    2: [],
    1: []
}

# 构建邻接矩阵
n_tasks = len(dependency_dict)
adj_matrix = np.zeros((n_tasks, n_tasks), dtype=int)
for i in range(1, n_tasks + 1):
    dependencies = dependency_dict[i]
    for dep in dependencies:
        if isinstance(dep, tuple):  # 或关系
            for j in dep:
                adj_matrix[j-1, i-1] = 1
        else:  # 与关系
            adj_matrix[dep-1, i-1] = 1
print(adj_matrix)
# 计算每个任务的入度
in_degree = np.sum(adj_matrix, axis=0)

# 拓扑排序
result = []
stack = [i+1 for i in range(n_tasks) if in_degree[i] == 0]
while stack:
    node = stack.pop()
    result.append(node)
    for i in range(n_tasks):
        if adj_matrix[node-1, i] == 1:
            in_degree[i] -= 1
            if in_degree[i] == 0:
                stack.append(i+1)
print(result)
# 构建任务链
task_chains = []
for i in range(n_tasks):
    if i == 0 or in_degree[result[i]-1] > 0:
        continue
    task_chain = [result[i]-1]
    for j in range(i+1, n_tasks):
        if adj_matrix[result[j]-1, task_chain[-1]] == 1:
            continue
        task_chain.append(result[j]-1)
        if len(task_chain) > 1 and isinstance(dependency_dict[task_chain[-1]+1][0], tuple):
            # 处理或关系
            task_chains.append(task_chain.copy())
        if len(task_chain) > 1 and isinstance(dependency_dict[task_chain[-1]+1][0], int):
            # 处理与关系
            while len(task_chain) > 1 and isinstance(dependency_dict[task_chain[-2]+1][0], int):
                task_chain.pop(-2)
            task_chains.append(task_chain.copy())
    task_chain.pop()

# 输出结果
for chain in task_chains:
    chain_str = "->".join(str(task+1) for task in chain)
    print(chain_str)


[[0 0 0 1 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[3, 2, 6, 1, 5, 4, 7, 9, 8]


IndexError: list index out of range

In [44]:
import queue

q = queue.Queue()

# 添加一些元素到队列
q.put(1)
q.put(2)
q.put(3)


In [47]:
# 获取队列中的所有元素并放入列表中
items = []
while not q.empty():
    item = q.get()
    items.append(item)

# 遍历列表并依次将元素放回队列中
for item in items:
    print(item)
    q.put(item)

1
2
3
